### ISSUE TITLE
Missing or invalid credentials accessing /auth/v1/admin/generate_link without apikey header

### ISSUE THREAD

**Issue by Inzeppelin** [burggraf/supabase-roll-your-own-auth#1]
Hi, thanks for your snippet! It was really useful for our project.

Everything worked as expected until 19.05, but now we've got `Missing or invalid credentials` error.

For some reason in your snippet `apikey` is sent as a query. Moreover, there is `SUPABASE_SERVICE_KEY` instead public key.

```
SUPABASE_API_URL || '/auth/v1/admin/generate_link?apikey=' || SUPABASE_SERVICE_KEY,
```

Now it looks like `apikey` should be sent as a header and it is required for `generate_link` endpoint.

I would suggest to change your snippet to:

```
http (('POST', 
        SUPABASE_API_URL || '/auth/v1/admin/generate_link?apikey=' || SUPABASE_SERVICE_KEY,
        ARRAY[
           http_header ('Authorization',  'Bearer ' || SUPABASE_SERVICE_KEY),
           http_header ('apikey',  SUPABASE_API_KEY),
        ], 
        'application/json', 
        payload::text
    ))
```

and add `SUPABASE_API_KEY` to `keys` table.

I can provide pull request if you approve this change.

Thanks!

**Comment by burggraf** [comment]
So are you saying something has changed on the Supabase side?  Can you point to a particular release so I can track this down?

**Comment by burggraf** [comment]
In your post above, you refer to both:
`SUPABASE_SERVICE_KEY` and `SUPABASE_API_KEY`, there should only be one key used in the call, I think.  And I don't think `apikey` needs to be sent in both the querystring and the header.

**Comment by Inzeppelin** [comment]
> So are you saying something has changed on the Supabase side? Can you point to a particular release so I can track this down?

Probably so. Unfortunately, I can't provide release, because I'm not aware of all technical details of supabase. I have no idea which particular code stands behind admin api functions and how release cycle is built.

> In your post above, you refer to both: `SUPABASE_SERVICE_KEY` and `SUPABASE_API_KEY`, there should only be one key used in the call, I think. And I don't think `apikey` needs to be sent in both the querystring and the header.

This doc says the same: 
https://github.com/supabase/gotrue#post-admingenerate_link, but I can confirm that it doesn't work like this. Here is my try:

```
curl -X POST 'https://{SUPABASE_API_URL}/auth/v1/admin/generate_link' \                                                              
-H "Authorization: Bearer {SUPABASE_SERVICE_KEY}" \
-H "Content-Type: application/json" \
-d '{
  "email": "{USER_EMAIL}",
  "type": "recovery" 
}'
```

It gives `Missing or invalid credentials.`

But this code works as expected:

```
curl -X POST 'https://{SUPABASE_API_URL}/auth/v1/admin/generate_link' \
-H "apikey: {SUPABASE_API_KEY}" \                 
-H "Authorization: Bearer {SUPABASE_SERVICE_KEY}" \
-H "Content-Type: application/json" \
-d '{
  "email": "{USER_EMAIL}",
  "type": "recovery" 
}'
```

Could you please check it on your side? Is it still working for you without `apikey` header?

**Comment by burggraf** [comment]
I think our auth team did change the links internally to require the apikey.  Could you do a PR here in this repo with that change?  Thanks for helping track this down!  Awesome work!

**Comment by Inzeppelin** [comment]
Please check suggested changes in PR https://github.com/burggraf/supabase-roll-your-own-auth/pull/2

**Comment by burggraf** [comment]
What's the difference between `SUPABASE_SERVICE_KEY` and `SUPABASE_API_KEY` here? Aren't they the exact same key used twice in this case?  As I recall, it's the same key that just needs to appear both in the `apikey` and `Authorization: Bearer` headers, no?

**Comment by Inzeppelin** [comment]
Answered in PR.

**Comment by burggraf** [comment]
I've merged in your changes.  Great work here, thanks so much for helping out here!
